"""add replies and parents

Revision ID: dc8540b5a430
Revises: c4fe58d1787d
Create Date: 2023-03-22 13:13:25.677253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8540b5a430'
down_revision = 'c4fe58d1787d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('parent_tweet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'tweets', ['parent_tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'parent_tweet_id')
    # ### end Alembic commands ###
