"""remove user_id from View table

Revision ID: df25103132ce
Revises: c9276047337c
Create Date: 2023-03-24 17:47:59.516858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df25103132ce'
down_revision = 'c9276047337c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('views_user_id_fkey', 'views', type_='foreignkey')
    op.drop_column('views', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('views_user_id_fkey', 'views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
